# Generated by Django 5.1.1 on 2025-02-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='lyrics',
        ),
        migrations.AddField(
            model_name='song',
            name='lyrics_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='songs/'),
        ),
    ]
