# Generated by Django 5.1.1 on 2025-02-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_song_lyrics_song_lyrics_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='lyrics_json',
        ),
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
